tap "homebrew/bundle"

# Core developer tools
brew "git"
brew "go"
brew "gh"
brew "tmux"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "jq"
brew "zoxide"
brew "starship"
brew "mise"
brew "wget"
brew "curl"
brew "tree"
brew "htop"
brew "node"
brew "python"
brew "uv"

# Useful developer tools inferred from this Mac
brew "act"
brew "bitwarden-cli"
brew "clojure"
brew "cloudflared"
brew "doctl"
brew "firebase-cli"
brew "gemini-cli"
brew "git-lfs"
brew "glab"
brew "gnupg"
brew "imagemagick"
brew "lua"
brew "nvm"
brew "pandoc"
brew "pre-commit"
brew "prettier"
brew "tesseract"
brew "yarn"

# Apps
cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "ghostty"
cask "docker"
cask "rectangle"
cask "raycast"
cask "google-chrome"
cask "firefox"

# Useful apps inferred from this Mac
cask "alt-tab"
cask "bitwarden"
cask "codex"
cask "cursor"
cask "gcloud-cli"
cask "hiddenbar"
cask "iterm2"
cask "karabiner-elements"
cask "keepassxc"
cask "miniconda"
cask "ngrok"
cask "notunes"
cask "signal"
cask "stats"
cask "sublime-text"
cask "utm"
cask "vlc"
