# Split panes using | and -
# Set the prefix to Ctrl+a
set -g prefix C-a
# Unbind the default Ctrl+b
unbind C-b
# Ensure we can still send Ctrl+a to other apps (by pressing it twice)
bind C-a send-prefix
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Set inactive pane background to a slightly different shade
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'
set-option -g renumber-windows on
set -g mouse on
set -g history-limit 50000

# Open URLs from pane: prefix + u
bind u run-shell "tmux capture-pane -J -p -S - > /tmp/tmux-pane-content" \; display-popup -E "~/bin/tmux-open-url"